# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resto',
            old_name='operation',
            new_name='opening_hour',
        ),
        migrations.AddField(
            model_name='resto',
            name='closing_hour',
            field=models.TimeField(null=True),
        ),
    ]
