# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belize', '0002_auto_20160610_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='resto',
            name='days_open',
            field=models.TextField(blank=True),
        ),
    ]
