# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belize', '0003_resto_days_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resto',
            old_name='days_open',
            new_name='mon_open',
        ),
        migrations.AddField(
            model_name='resto',
            name='fri_open',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resto',
            name='sat_open',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resto',
            name='sun_open',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resto',
            name='thu_open',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resto',
            name='tue_open',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resto',
            name='wed_open',
            field=models.TextField(blank=True),
        ),
    ]
