# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belize', '0004_auto_20160612_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resto',
            name='fri_open',
        ),
        migrations.RemoveField(
            model_name='resto',
            name='mon_open',
        ),
        migrations.RemoveField(
            model_name='resto',
            name='sat_open',
        ),
        migrations.RemoveField(
            model_name='resto',
            name='sun_open',
        ),
        migrations.RemoveField(
            model_name='resto',
            name='thu_open',
        ),
        migrations.RemoveField(
            model_name='resto',
            name='tue_open',
        ),
        migrations.RemoveField(
            model_name='resto',
            name='wed_open',
        ),
        migrations.AddField(
            model_name='resto',
            name='days_open',
            field=models.TextField(blank=True),
        ),
    ]
